### PR TITLE
Migrate to null-safety

### PR DESCRIPTION
**Pull request by LeonardoRosaa**
Starting pull request to migrate package to null safety version.

To do:
- [x] Migrate to null safety;
- [x] Test in IOS plataform;
- [x] Test in Android plataform.

### CODE REVIEW

**Comment by GRBurst** [comment]
@pichillilorenzo any updates on this? Is this library still maintained?

**Comment by sagargpt** [comment]
Is anyone actively reviewing the PR? 
There seems to be no assigne or reviewers attached.

**Comment by juliavi** [comment]
Is anyone reviewing this and going to merge? @pichillilorenzo

**Comment by juliavi** [comment]
@pichillilorenzo

**Comment by Nei1eveN** [comment]
any update on this?

**Comment by LeonardoRosaa** [comment]
Hey folks, I writing a similar package, from here after some weeks I launch first release for Android only. I doing make a skeleton first to launch and open for public.

But I warning, I need help to write for IOS platform.

Thanks!

**Comment by LeonardoRosaa** [comment]
@juliavi @Nei1eveN @GRBurst @sagargpt I did launch first release: https://github.com/LeonardoRosaa/have_app

**Comment by Yash-Garg** [comment]
Hey, I recently refactored this whole package almost. Here's the link if anyone wants to use it - https://pub.dev/packages/appcheck

**Comment by yash-garg** [comment]
> any update on this?

Hey, I recently refactored this whole package in Kotlin. Here's the link if you want to use it - https://github.com/Yash-Garg/AppCheck

Works for both Android and iOS, including null safety.

**Comment by rahuldange09** [comment]
Great! Thanks.
Until @pichillilorenzo merges this PR.
Use it like this

```ruby
  flutter_appavailability:
    git: https://github.com/LeonardoRosaa/flutter_appavailability
```

**Pull request closed without merging**
